services:
  cloud_ip_receiver:
    image: cloud-ip-receiver:latest
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./last_ip.txt:/app/last_ip.txt      
    environment:
      FLASK_APP: cloud_ip_receiver.py
    restart: always
